export const CH = {
  profileGet: 'profile:get',
  profileSetName: 'profile:setName',
  gamGetState: 'gamification:getState',
  gamRecordActivity: 'gamification:recordActivity',
  gamBuyEgg: 'gamification:buyEgg',
  gamBuyTreat: 'gamification:buyTreat',
  gamBuyItem: 'gamification:buyItem',
  gamHatchEgg: 'gamification:hatchEgg',
  gamSetActivePet: 'gamification:setActivePet',
  gamEquipItem: 'gamification:equipItem',
  gamUnequipItem: 'gamification:unequipItem',
  gamRenamePet: 'gamification:renamePet',
  taxonomyList: 'taxonomy:list',
  qbankGetComposerData: 'qbank:getComposerData',
  qbankStartSession: 'qbank:startSession',
  qbankSubmitAnswer: 'qbank:submitAnswer',
  qbankCompleteSession: 'qbank:completeSession',
  qbankToggleFlag: 'qbank:toggleFlag',
  qbankGetDashboard: 'qbank:getDashboard'
} as const
