export const CH = {
  profileGet: 'profile:get',
  profileSetName: 'profile:setName',
  gamGetState: 'gamification:getState',
  gamRecordActivity: 'gamification:recordActivity',
  gamBuyEgg: 'gamification:buyEgg',
  gamBuyTreat: 'gamification:buyTreat',
  gamBuyItem: 'gamification:buyItem',
  gamHatchEgg: 'gamification:hatchEgg',
  gamSetActivePet: 'gamification:setActivePet',
  gamEquipItem: 'gamification:equipItem',
  gamUnequipItem: 'gamification:unequipItem',
  gamRenamePet: 'gamification:renamePet',
  contentGetOutline: 'content:getOutline',
  contentGetLesson: 'content:getLesson',
  contentMarkViewed: 'content:markViewed',
  contentMarkComplete: 'content:markComplete',
  contentLessonForTaxonomy: 'content:lessonForTaxonomy',
  taxonomyList: 'taxonomy:list',
  taxonomyTags: 'taxonomy:tags',
  qbankStartSession: 'qbank:startSession',
  qbankSubmitAnswer: 'qbank:submitAnswer',
  qbankCompleteSession: 'qbank:completeSession',
  qbankToggleFlag: 'qbank:toggleFlag',
  qbankDashboard: 'qbank:dashboard',
  qbankQuestionsForTaxonomy: 'qbank:questionsForTaxonomy'
} as const
