// AUTO-GENERATED by scripts/gen-pet-sprites.mjs — do not edit by hand.
// Per-creature, per-state sprite-strip metadata: how many frames each `pets/<key>/<state>.png`
// strip holds and how long each frame shows. <Pet> uses this to drive the CSS sprite animation.

export interface FrameSpec { frames: number; durationMs: number }

export const PET_FRAMES: Record<string, Record<string, FrameSpec>> = {
  "dog": {
    "happy": {
      "frames": 6,
      "durationMs": 180
    },
    "sleeping": {
      "frames": 6,
      "durationMs": 180
    },
    "sad": {
      "frames": 6,
      "durationMs": 180
    },
    "angry": {
      "frames": 6,
      "durationMs": 180
    },
    "eating": {
      "frames": 6,
      "durationMs": 180
    }
  },
  "cat": {
    "happy": {
      "frames": 6,
      "durationMs": 180
    },
    "sleeping": {
      "frames": 6,
      "durationMs": 180
    },
    "sad": {
      "frames": 6,
      "durationMs": 180
    },
    "angry": {
      "frames": 6,
      "durationMs": 180
    },
    "eating": {
      "frames": 6,
      "durationMs": 180
    }
  },
  "axolotl": {
    "happy": {
      "frames": 6,
      "durationMs": 180
    },
    "sleeping": {
      "frames": 6,
      "durationMs": 180
    },
    "sad": {
      "frames": 6,
      "durationMs": 180
    },
    "angry": {
      "frames": 6,
      "durationMs": 180
    },
    "eating": {
      "frames": 6,
      "durationMs": 180
    }
  },
  "pig": {
    "happy": {
      "frames": 6,
      "durationMs": 135
    },
    "sleeping": {
      "frames": 6,
      "durationMs": 135
    },
    "sad": {
      "frames": 6,
      "durationMs": 135
    },
    "angry": {
      "frames": 6,
      "durationMs": 135
    },
    "eating": {
      "frames": 6,
      "durationMs": 135
    }
  },
  "frog": {
    "happy": {
      "frames": 6,
      "durationMs": 140
    },
    "sleeping": {
      "frames": 6,
      "durationMs": 140
    },
    "sad": {
      "frames": 6,
      "durationMs": 140
    },
    "angry": {
      "frames": 6,
      "durationMs": 140
    },
    "eating": {
      "frames": 6,
      "durationMs": 140
    }
  },
  "capybara": {
    "happy": {
      "frames": 6,
      "durationMs": 140
    },
    "sleeping": {
      "frames": 6,
      "durationMs": 140
    },
    "sad": {
      "frames": 6,
      "durationMs": 140
    },
    "angry": {
      "frames": 6,
      "durationMs": 140
    },
    "eating": {
      "frames": 6,
      "durationMs": 140
    }
  }
}
